### ISSUE TITLE
stocks don't work with bokeh-master (soon to be 0.11)

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh-demos#12]
I see we had to add the method `crossdomain` in the examples: https://github.com/bokeh/bokeh/blob/master/examples/plotting/file/ajax_source.py#L32 after the server update. 

This definitely is needed to replace `bokeh.server.crossdomain` (https://github.com/bokeh/bokeh-demos/blob/master/stocks/flask_server_minutes.py#L13) but doing it same didn't get me all the way there and I didn't have time to look further.

**Comment by foobarbecue** [comment]
Urgh, was this never fixed? Is there a workaround? I'm new to bokeh and would like to use the stocks example...

**Comment by birdsarah** [comment]
i believe this example pre-dates the new bokeh server. I would recommend checking out the stocks examples here:
* http://bokeh.pydata.org/en/latest/docs/gallery.html
* https://github.com/bokeh/bokeh/tree/master/examples/app

**Comment by phobson** [comment]
With a fresh install of bokeh from conda, and a freshly cloned bokeh repository, I can confirm that the stocks example works after you're sure to run download_sample_data.py

**Comment by birdsarah** [comment]
Thanks @phobson!

**Comment by foobarbecue** [comment]
The stock example at https://github.com/bokeh/bokeh/tree/master/examples/app/stocks does work, but there's almost nothing there. It's completely different from the stocks example at https://github.com/bokeh/bokeh-demos/tree/master/stocks . The bokeh-demos version has ajax requests, a Flask app, etc. As far as I can tell, this was the only available working example of AjaxDataSource.

**Comment by birdsarah** [comment]
OK. I've reopened the issue if you're saying it's not working. If you have time to look at it we certainly appreciate the help.

**Comment by foobarbecue** [comment]
Well, what's the story on bokeh-demos? Is this repository being deprecated in favor of the examples in the bokeh repository? If so the best thing would be to add a feature request issue to the other repository asking that we implement all the stuff that the old stocks example had.

Unfortunately it'll be sometime before I can contribute code... I only started with bokeh today.

**Comment by foobarbecue** [comment]
Oh, there's a [PR ](https://github.com/bokeh/bokeh-demos/pull/23 ) which says it fixes this issue. I guess you might as well merge it.

**Comment by foobarbecue** [comment]
PR doesn't work with python 3 and also appears to have issues with the latest pandas.

**Comment by bryevdv** [comment]
> Well, what's the story on bokeh-demos? Is this repository being deprecated 

I think there is no other option. Trying to maintain this repo separately requires more person-power than we have.
