### ISSUE TITLE
Happiness demo gets a 'OSError at /5/individual'

### ISSUE THREAD

**Issue by pfennema** [bokeh/bokeh-demos#14]
When trying to get the new happiness demo running (I know it is still in dev), I get an OSError.
When tracing the possible issue I see a connect issue within the tornado server:

            try:
                old_wakeup_fd = signal.set_wakeup_fd(self._waker.write_fileno())
                if old_wakeup_fd != -1:
                    # Already set, restore previous value.  This is a little racy,
                    # but there's no clean get_wakeup_fd and in real use the
                    # IOLoop is just started once at the beginning.
                    signal.set_wakeup_fd(old_wakeup_fd)
                    old_wakeup_fd = None
            except ValueError:
                
                # Non-main thread, or the previous value of wakeup_fd
                # is no longer valid.
                old_wakeup_fd = None

The signal.set_wakeup_fd raises a ValueError exception and the exception is because it is not on the main thread. Any idea to resolve this?
It could also be a different mechanism to connect from the django app to the bokeh server, but do not see where the connection is actually made.

I have bokeh 0.11dev05 installed locally on ubuntu 14.04.

To further clarify: The original error I got was the following:
***url should be the http or https URL for the server, not the websocket URL*** 
When changing the url in 'get_bokeh_script from ws:// to http:// I get the OSError.
Furthermore, the response in the log of the bokeh server is the following:
INFO:bokeh.command.subcommands.serve:Starting Bokeh server on port 5006 with applications at paths ['/individual']
***WARNING:tornado.access:404 GET /individual/ws/ws?bokeh-protocol-version=1.0&bokeh-session-id=8qhKqwSpd9ya3mFyurJFIIsuJ5OY9jhY80Y8 (::1) 1.65ms***

Thanks!

**Comment by bryevdv** [comment]
Hi @pfennema This demo is still under active development and things in the main repo are as well. We will be working on this next week and after the code freeze. It will be ready for the release on the 6th but I can't say anything else in the short term.

**Comment by pfennema** [comment]
Thanks! Anxiously awaiting the demo as we'd like to integrate with Django. Keep up the great work :+1:

**Comment by birdsarah** [comment]
@pfennema this should be fixed now. Please run with latest bokeh and check the announcement coming v. soon :D

**Comment by pfennema** [comment]
Many, many thanks!
