### ISSUE TITLE
Unused sessions.

### ISSUE THREAD

**Issue by bs7** [bokeh/bokeh-demos#22]
For every request, you open a new session with get_bokeh_script(). This results in accumulating unused sessions on the Bokeh serve.

**Comment by bryevdv** [comment]
Bokeh server sessions expire after a (configurable) period of disuse. Are you saying that they don't? If so, can you describe how you verified this?

**Comment by bs7** [comment]
Here my test (Bokeh 0.11.1):

<b>START:<b>

/bokeh serve --allow-websocket-origin 127.0.0.1:5000
/python manage.py runserver 5000


<b>LOG:<b>

11:04: DEBUG:bokeh.server ... 0 clients connected --> / has 0 sessions with 0 unused.

11:05: 5 times click on "Carey"
11:05: 1 clients connected --> / has 5 sessions with 4 unused.

11:10: 1 clients connected --> / has 5 sessions with 4 unused.

11:11: click on "Home" --> connection closed: code 1001, reason=None
11:11: 0 clients connected --> / has 5 sessions with 4 unused.

11:21: 0 clients connected --> / has 5 sessions with 4 unused.
11:21: Close Browser.

11:31:  0 clients connected --> / has 5 sessions with 4 unused.

<b>RESULT:<b>

Sessions seem to persist.

**Comment by birdsarah** [comment]
@bs7, i'm assuming you're looking at the happiness demo. between v1 and v2 (https://github.com/bokeh/bokeh-demos/pull/20) I realized my mistake and I now make sure to close the session that was being opened by get_bokeh_script() https://github.com/bokeh/bokeh-demos/blob/happiness_v2/happiness/happiness/bokeh_utils.py#L19.

You can see my lessons learned here: http://nbviewer.jupyter.org/github/bokeh/bokeh-demos/blob/happiness_v2/happiness/Building%20happiness.ipynb

**Comment by bs7** [comment]
@birdsarah: I look at happiness_v2 and I don't think it is an issue of your example, please repeat the test I did and look if the sessions are still there even when you close your browser. With my setup this is the case because they never timeot.
