### ISSUE TITLE
Happiness app needed extra flag in bokeh.sh?

### ISSUE THREAD

**Issue by benlaken** [bokeh/bokeh-demos#25]
I had to add `--allow-websocket-origin=127.0.0.1:8001` to get the app to display to bokeh.sh script. Also, I had to migrate the database (which maybe should be in the readme?): `./manage.py migrate`.

**Comment by mathieuboudreau** [comment]
Plots were not working until I added the tag too, this should be an easy fix.

**Comment by djpugh** [comment]
In windows it seems the default django port is 8000 so it would also need --allow-websocket-origin=127.0.0.1:8000
