### ISSUE TITLE
No module named crossdomain

### ISSUE THREAD

**Issue by nickos556** [bokeh/bokeh-demos#29]
Hi I get the following error:

(E:\NICK\LOCAL\apps\anaconda2-2.5.0) E:\NICK\LOCAL\src\bokeh-demos\stocks>python flask_server_minutes.py
Traceback (most recent call last):
  File "flask_server_minutes.py", line 13, in <module>
    from bokeh.server.crossdomain import crossdomain
ImportError: No module named crossdomain

This is running bokeh version 0.12.3.

Any ideas?

thanks!

**Comment by stvn66** [comment]
I do not see a `crossdomain.py` file in [`bokeh/server/`](https://github.com/bokeh/bokeh/tree/master/bokeh/server).  I expect this is a change that did not get propagated to the [demo you are running](https://github.com/bokeh/bokeh-demos/blob/master/stocks/flask_server_minutes.py).  There is a definition for `crossdomain` in [`bokeh/examples/howto/ajay_source.py](https://github.com/bokeh/bokeh/blob/9650b109b62d385d372eecc1f9d5a511bf4a3d49/examples/howto/ajax_source.py) but I do not think this is part of the installation.  

Someone who is familiar with `crossdomain`, what are your thoughts?

**Comment by schultzmattd** [comment]
There's a discussion on this [here](https://github.com/bokeh/bokeh-demos/issues/12). Looks like this repo is deprecated. There's a pointer to a new stocks example in that thread (not sure how similar it is to the one here) that I got running in a couple of minutes.

**Comment by bryevdv** [comment]
Yes, as soon as I can catch a breath we'll start a process to migrate and/or delete this repo, and keep all examples in the main repo where they can actually have a chance to be maintained.

**Comment by bryevdv** [comment]
I have deleted everything except `happiness` and have added banner warnings about the repo begin outdated. I am going to close this and all other issues now. Once there is a somewhat comparable demo in the main repo I will delete this one.
