### ISSUE TITLE
Design for top level demo-runner

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh-demos#4]
@bokeh/dev I would like to propose codifying some conventions and formats that all the contributed demos can adhere to, so that users can simply execute a "demo explorer" at the top level and be automatically presented with a page that links to all the demos.

**Comment by almarklein** [comment]
+1

**Comment by fpliger** [comment]
+1000

can definitely have some fun playing with it :-)

**Comment by bryevdv** [comment]
Will try to flesh out a proposal tomorrow with @maggie-m for folks to comment on.

**Comment by fpliger** [comment]
@bryevdv ok. I didn't read the full comment on #2 so I assigned this to myself already (as I thought I have some code I could reuse for this).

Honestly I didn't think about something like the interactive tester at first... More something like a web version of the chaco demo app. Does it make sense?

If I manage to find the code I'm thinking about I may be able to share an example...

**Comment by bryevdv** [comment]
Oh, it's intended to be a web demo app, there's just some code in the interactive tester for running process that might be useful.

**Comment by damianavila** [comment]
:+1: as well...
